compile_act : 
	cp ../Proofs/Holmakefile_ACT ../Proofs/Holmakefile; 
	Holmake
compile_union :
	cp ../Proofs/Holmakefile_Union ../Proofs/Holmakefile;
	Holmake
compile_actVar :
	cp ../Proofs/Holmakefile_ACTvar ../Proofs/Holmakefile;
	Holmake
compile_victoria :
	cp ../Proofs/Holmakefile_Victoria ../Proofs/Holmakefile;
	Holmake
compile_cade :
	cp ../Proofs/Holmakefile_CADE ../Proofs/Holmakefile;
	Holmake


clean :
	rm -rf *Theory* .hollogs .HOLMK ../Tempo/*Theory ../Tempo/.hollogs ../Tempo/.HOLMK ../Checker/*Theory* ../Checker/.hollogs ../Checker/.HOLMK ../Parser/*Theory* ../Parser/.hollogs ../Parser/.HOLMK  ../CheckerTrans/*Theory* ../CheckerTrans/.hollogs ../CheckerTrans/.HOLMK  ../Proofs/*Theory* ../Proofs/.hollogs ../Proofs/.HOLMK ../ACT_STV/*Theory* ../ACT_STV/.hollogs ../ACT_STV/.HOLMK ../Victoria_STV/*Theory* ../Victoria_STV/.hollogs ../Victoria_STV/.HOLMK  ../Union_STV/*Theory* ../Union_STV/.hollogs ../Union_STV/.HOLMK  ../ACT_STV_Variant/*Theory* ../ACT_STV_Variant/.hollogs ../ACT_STV_Variant/.HOLMK ../Auxiliary/*Theory* ../Auxiliary/.hollogs ../Auxiliary/.HOLMK proofs/*Theory* proofs/.hollogs proofs/.HOLMK ../CADE_STV/*Theory* ../CADE_STV/.HOLMK ../CADE_STV/.hollogs  

check_count: check_count.o basis_ffi.o
